### ISSUE TITLE
A few mods to look at. :)

### ISSUE THREAD

**Issue by Chatan1** [KelleyEngineering/MonsterPack-Reloaded#2]
I figured its better to put them all in one instead of opening many and go looking for them.

This is Sparta.. well maybe not.

One to look at, I for one enjoyed the shields in Dungeon Tactics, but figured its time for something else that adds a lot cooler shields, more so when going down into the other dungeons.

Also to go with those Spartan Shields, we have Spartan Weaponry, because why not? If you plan to go full out Spartan, then get the weapons as well.

https://minecraft.curseforge.com/projects/spartan-weaponry
https://minecraft.curseforge.com/projects/spartan-shields
---------------------------------------------------------------------------------------------------
Next Rope Bridge

Obviously people enjoy climbing, and jumping into pools of water at the bottom of a ravine/gorge. But I for one have been interested in the easy way to get across, and in this case Rope Bridge.

https://minecraft.curseforge.com/projects/rope-bridge
---------------------------------------------------------------------------------------------

Next is the Aliens vs Predator mod.

Now this is one that may be too much for the server and people's comp, which I totally understand but also a mod that needs a lot more polishing in my opinion. As much as I love AvP franchises. This is mod is 50/50 in the way that I would love to get it vs the quality and the resources.

http://www.mc-mod.net/alien-vs-predator-mod/
--------------------------------------------------------------------------------------------------------

Next is Tech Guns Mod

Too be honest, it is very hard to find a mod that has good guns in. There is of course Flans, Modern Warfare, but none of them are high tech and what can be better then shooting a high tech weapon? The only other mod that would be good which is not being updated anymore is Matter Overdrive, so this Tech Guns Mod appeals to me.

http://www.mc-mod.net/tech-guns-mod/
----------------------------------------------------------------------------------------------------------------#

Next is the Grapple Hooks mod.

It is a little like the Rope Bridge in a way that is makes things a lot easier to move around. I more so if you find yourself at the bottom of high mountains or a crag and jumping block to block can be very tedious. But it is worth looking into, plus it being simple the resources should be fine on it.

http://www.mc-mod.net/grapple-hooks-mod/
---------------------------------------------------------------------------------------------------------

Ad Inferos Mod

Supposedly the way the Nether was actually meant to be originally it says.

http://www.mc-mod.net/ad-inferos-mod/

I think that would be enough for now. These would need to be checked out anyway, though the website (which I will include) says 1.12. Obviously its hard to say if they actually mean it or not, as I once said Matter Overdrive isnt in 1.12, but on the website it says it is. Here is the website http://www.mc-mod.net/tag/armors-tools-and-weapons/

Ps. Also I apologise for the web addresses not being linked.

P.P.S Not sure where to post this, so posted in the same place as Shadow.

**Comment by KelleyEngineering** [comment]
Alien vs Predator and tech-guns do not fit the theme of the Pack. They won't be added
There is already a grapple hook in the pack.
NetherEX is plenty enough for Nether Exploration

I'll look into the Spartan Stuff, Thanks Chatan

**Comment by Chatan1** [comment]
Np, all of them are worth looking at. But most of those apart from the Spartan items are a little op anyway. I will keep looking. Also see if there are any other dungeons.

**Comment by Ranger1230** [comment]
Woot might be a nice one to add. It allows players to make mob farms that don't spawn any entities so its much more server friendly.
