### ISSUE TITLE
Cannot craft bedrock

### ISSUE THREAD

**Issue by Ranger1230** [KelleyEngineering/MonsterPack-Reloaded#5]
Looking in the custom recipes, the bedrock recipe is broken. it's missing a closing parenthesis before the semi-colon. This why we aren't able to craft it (unless you weren't sure about adding it yet).

currently the recipe is:
recipes.addshaped(<minecraft:bedrock>, [[<extrautils2:compressedcobblestone:1>, <minecraft:obsidian>, <extrautils2:compressedcobblestone:1>], [<extrautils2:compressedgravel:1>, <extrautils2:compressedcobblestone:2>, <extrautils2:compressedgravel:1>], [<extrautils2:compressedcobblestone:1>, <minecraft:obsidian>, <extrautils2:compressedcobblestone:1>]];

it should be:
recipes.addshaped(<minecraft:bedrock>, [[<extrautils2:compressedcobblestone:1>, <minecraft:obsidian>, <extrautils2:compressedcobblestone:1>], [<extrautils2:compressedgravel:1>, <extrautils2:compressedcobblestone:2>, <extrautils2:compressedgravel:1>], [<extrautils2:compressedcobblestone:1>, <minecraft:obsidian>, <extrautils2:compressedcobblestone:1>]]);

**Comment by KelleyEngineering** [comment]
Fixed
